{% extends "base.phtml" %}
{% block title %}Two Trees Buyback{% endblock %}
{% block content %}
<div class="row">
	<div class="card mx-auto mt-5 bg-light">
		<div class="card-body">
			<a href="https://forum.pleaseignore.com/topic/109678-active-two-trees-buyback/">TEST Forum Post</a>
<pre>
Buyback 90% JBV (+2% in T5Z)
Salvage, Loot, Rat Poop, Explo, Triglavian, Faction, Deadspace, Implants, Mods, Rigs, Limited BPCs, etc
Servicing all of Delve, Period Basis, and Western Querious

Overseer Effects:
23rd 123m
22nd 94m
21st 74m
20th 56m
19th 47m
All others 90%(+2%) NPC Buy

Red/Blue Loot:
Triglavian Survey Database       92k
Ancient Coordinates Database  1,380k
Neural Network Analyzer         184k
Sleeper Data Library.           460k
Sleeper Drone AI Nexus        4,600k

No other BPCs, PI, ore, or minerals.

The Easy Way: Create a contract to Two Trees with a price of 0. I do the math and deposit your isk.
The Hard Way: Create an Evepraisal of the items, multiply 'Total Buy Value' by 0.9 (use 0.92 if located in T5Z), then create a contract with the calculated price.

Note that with The Easy Way, I use combined Jita+Perimeter pricing due to ranged buy orders in TTT. This generally guarantees a higher payout than the typical Jita-only appraisal. It is also no longer necessary to seperate out OPEs or red/blue loot with The Easy Way.
</pre>
		</div>
	</div>
</div>
{% endblock %}
