<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta property="og:type" content="website">
		<meta property="og:url" content="https://twotrees.space">
		<meta property="og:title" content="Two Trees Buyback">
		<meta property="og:description" content="Buying your random stuff in and around TEST space.">
		<meta property="og:image" content="https://twotrees.space/2tree_sm.png">
		<title>{% block title %}{% endblock %}</title>
		<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="style.css">
		<link rel="shortcut icon" type="image/jpg" href="2tree_sm.png"/>
	</head>
	<body class="bg-dark">
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
			<div class="container">
				<a class="navbar-brand" href="/"><img class="nav-icon" src="2tree_sm.png">Two Trees Buyback</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<ul class="navbar-nav ms-auto mb-2 mb-lg-0">
						<li class="nav-item"><a class="nav-link" href="/calculator">Calculator</a></li>
						<li class="nav-item"><a class="nav-link" href="/">About</a></li>
					</ul>
				</div>
			</div>
		</nav>
		<div class="container">
{% block content %}{% endblock %}
		</div>
		<div class="modal fade" id="warning-modal" tabindex="-1" role="dialog">
		  <div class="modal-dialog" role="document">
			<div class="modal-content">
			  <div class="modal-header bg-warning">
				<h5 class="modal-title" id="modal-title"></h5>
			  </div>
			  <div class="modal-body">
				<pre id="modal-text"></pre>
			  </div>
			</div>
		  </div>
		</div>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
		<script type="text/javascript" src="app.js"></script>
	</body>
</html>
