{% extends "base.phtml" %}
{% block title %}Two Trees Calculator{% endblock %}
{% block content %}
<div class="row">
	<div class="card mx-auto mt-5 bg-light">
		<div class="card-body">
			<p class="alert-warning">Note: Lines must be in the format "item&lt;tab&gt;quantity" until I get around to implementing more advanced parsing. Copying items directly from a hangar or contract will have this format.</p>
			<div class="input-group">
				<textarea id="paste-area" rows="15" cols="300" class="form-control" aria-label="paste area" placeholder="paste here" disabled></textarea>
			</div>
			<button id="appraise" class="btn btn-success btn-block" disabled>Appraise</button>
		</div>
	</div>
</div>
<div class="row">
	<div class="card mx-auto mt-5 bg-light">
		<div  id="results" class="card-body">
			T5ZI-S, ZA9-PY <h2 id="appraisal-estimate-prime">&#x01B6;</h1>
			Elsewhere <h2 id="appraisal-estimate-sub">&#x01B6;</h1>
			<p>See <a href="/rates#getting-paid">here</a> for how to get paid<p>
		</div>
	</div>
</div>
{% endblock %}
