{% extends "base.phtml" %}
{% block title %}Two Trees Buyback{% endblock %}
{% block content %}
<div class="row">
	<div class="card mx-auto mt-3 bg-light">
		<div class="card-body">
			<p>Please contact me in-game via evemail at <a target="_blank" href="https://evewho.com/character/96151338">Orome Aldaron</a> with any questions, comments, or disputes.</p>
			<p>TEST Alliance members can also reach me via our forums or Discord at the same name.</p>
		</div>
	</div>
</div>
{% endblock %}
