{% extends "base.phtml" %}
{% block title %}Two Trees Buyback{% endblock %}
{% block content %}
<div class="row">
	<div class="card mx-auto mt-3 bg-light">
		<div class="card-body">
			<p>Please contact me in-game via evemail at <a target="_blank" href="https://evewho.com/character/96151338">Orome Aldaron</a> with any questions, comments, or disputes. Contact may also be done through the CEO character <a target="_blank" href="https://evewho.com/character/2114247422">Ivon Kementari</a></p>
			<p>TEST Alliance members can also reach me via our forums or Discord at the same name.</p>
			<br>
			<a target="_blank" href="https://forum.pleaseignore.com/topic/109678-active-two-trees-buyback/">Link to the service post on the TEST Forums (requires TEST Auth)</a>
		</div>
	</div>
</div>
{% endblock %}
