{% extends "base.phtml" %}
{% block title %}Two Trees Buyback{% endblock %}
{% block content %}
<div class="row">
	<div class="card mx-auto mt-3 bg-light">
		<div class="card-body">
			<p><b>1. Why do your prices differ from other tools like <a target="_blank" href="https://evepraisal.com/">Evepraisal</a>?</b></p>
			<p class="px-3">I use a combination of prices from both Jita 4-4 and Perimeter TTT. This produces a more accurate estimate and generally guarantees a higher payout than the typical Jita-only appraisal.</p>
			<p><b>2. Do I need to separate items that payout at different rates?</b></p>
			<p class="px-3">No, my calculator will handle all of that automatically.</p>
			<p><b>3. Why does your rate on NPC items (OPEs, red, and blue loot) appear lower than other services?</b></p>
			<p class="px-3">It actually isn't! Other services use JBV to price these items, whereas I use the NPC buy price. There is roughly a 3% difference between them, so my 92% NPC rate is approximately the same as a 95% JBV rate!</p>
		</div>
	</div>
</div>
{% endblock %}
