{% extends "base.phtml" %}
{% block title %}Two Trees Buyback{% endblock %}
{% block content %}
<div class="row">
	<div class="card mx-auto mt-3 bg-light">
		<div class="card-body">
			<h4 id="getting-paid">How to get paid:</h4>
			<p><b>The Easy Way:</b> Create a contract to <a target="_blank" href="https://evemaps.dotlan.net/corp/Two_Trees">Two Trees</a> with a price of 0. I do all of the math and deposit your isk.</p>
			<p><b>The Slightly Harder Way:</b> Create a contract using the location-appropriate price produced by <a href="/">my calculator</a>.</p>
			<p><b>The Hardest Way:</b> Create an <a target="_blank" href="https://evepraisal.com/">Evepraisal</a> of the items, multiply 'Total Buy Value' by 0.9 (use 0.92 if located in a hub) or use the Price Percentage option in the gear menu, then create a contract with the calculated price. Note that you will NOT receive the higher rates on specific item groups with this method.</p>
		</div>
	</div>
</div>
{% endblock %}
