{% extends "base.phtml" %}
{% block title %}Two Trees Buyback{% endblock %}
{% block content %}
<div class="row">
	<div class="card mx-auto mt-3 bg-light">
		<div class="card-body">
			<p>Servicing all of <a target="_blank" href="https://evemaps.dotlan.net/map/Outer_Passage">Outer Passage<a></p>
			<p><b>Current Hub Systems:</b> <a target="_blank" href="https://evemaps.dotlan.net/map/Outer_Passage/T0DT-T">T0DT-T</a>, <a target="_blank" href="https://evemaps.dotlan.net/map/Outer_Passage/NEU-UD">NEU-UD</a></p>
			<h4>Rates:</h4>
			<table class="table table-sm">
				<thead>
					<tr>
						<th scope="col">Item Group</th>
						<th scope="col">Hub</th>
						<th scope="col">Non-Hub</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td class="table-secondary">Overseer Effects*</td>
						<td>91% NPC <b>(~95% JBV)</b></td>
						<td>89% NPC <b>(~93% JBV)</b></td>
					</tr>
					<tr>
						<td class="table-secondary">SCC Bonds</td>
						<td>91% NPC <b>(~95% JBV)</b></td>
						<td>89% NPC <b>(~93% JBV)</td>
					</tr>
					<tr>
						<td class="table-danger">Red Loot</td>
						<td>91% NPC <b>(~95% JBV)</b></td>
						<td>89% NPC <b>(~93% JBV)</td>
					</tr>
					<tr>
						<td class="table-primary">Blue Loot</td>
						<td>91% NPC <b>(~95% JBV)</b></td>
						<td>89% NPC <b>(~93% JBV)</td>
					</tr>
					<tr>
						<td>Salvage</td>
						<td>94% JBV</td>
						<td>92% JBV</td>
					</tr>
					<tr>
						<td>Datacores</td>
						<td>94% JBV</td>
						<td>92% JBV</td>
					</tr>
					<tr>
						<td>Decryptors</td>
						<td>94% JBV</td>
						<td>92% JBV</td>
					</tr>
					<tr>
						<td>Implants</td>
						<td>94% JBV</td>
						<td>92% JBV</td>
					</tr>
					<tr>
						<td>Skins</td>
						<td>94% JBV</td>
						<td>92% JBV</td>
					</tr>
					<tr>
						<td>Rat Poop</td>
						<td>92% JBV</td>
						<td>90% JBV</td>
					</tr>
					<tr>
						<td>Modules & Rigs</td>
						<td>92% JBV</td>
						<td>90% JBV</td>
					</tr>
					<tr class="table-success">
						<td>Everything Else</td>
						<td>92% JBV</td>
						<td>90% JBV</td>
					</tr>
				</tbody>
			</table>
			*see below for effective rates on higher tier OPEs<br><br>
			<table class="table table-sm">
				<thead>
					<tr>
						<th scope="col">Overseer Effects</th>
						<th scope="col">Effective Payout</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>23rd Tier</td>
						<td>122m</td>
					</tr>
					<tr>
						<td>22nd Tier</td>
						<td>92.5m</td>
					</tr>
					<tr>
						<td>21st Tier</td>
						<td>72.8m</td>
					</tr>
					<tr>
						<td>20th Tier</td>
						<td>55.7m</td>
					</tr>
					<tr>
						<td>19th Tier</td>
						<td>47m</td>
					</tr>
				</tbody>
			</table>
			<p class="text-danger"><b>Not accepting blueprints, PI, ore, minerals, fighters, or ships.</b> I sometimes accept ships and fighters on a limited basis, but please <a href="/contact">contact me</a> beforehand.</p>
		</div>
	</div>
</div>
{% endblock %}
