{% extends "base.phtml" %}
{% block title %}Two Trees Buyback{% endblock %}
{% block content %}
<div class="row">
	<div class="card mx-auto mt-5 bg-light">
		<div class="card-body">
			<p>Servicing all of <a target="_blank" href="https://evemaps.dotlan.net/map/Delve">Delve<a>, <a target="_blank" href="https://evemaps.dotlan.net/map/Period_Basis">Period Basis</a>, and <a target="_blank" href="https://evemaps.dotlan.net/map/Querious/F2OY-X,4-2UXV,L-FVHR,RKM-GE,DG-L7S,K4-RFZ,8-YNBE,E-VKJV,YQX-7U,QY1E-N,BX-VEX,B-7DFU">Western Querious<a></p>
			<p><b>Current Hub Systems:</b> <a target="_blank" href="https://evemaps.dotlan.net/map/Delve/T5ZI-S">T5ZI-S</a>, <a target="_blank" href="https://evemaps.dotlan.net/map/Delve/ZA9-PY">ZA9-PY</a></p>
			<h4>Rates:</h4>
			<table class="table table-sm">
				<thead>
					<tr>
						<th scope="col">Item Group</th>
						<th scope="col">Hub</th>
						<th scope="col">Non-Hub</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td class="table-secondary">Overseer Effects*</td>
						<td>92% NPC <b>(~95% JBV)</b></td>
						<td>90% NPC <b>(~93% JBV)</b></td>
					</tr>
					<tr>
						<td class="table-secondary">SCC Bonds</td>
						<td>92% NPC <b>(~95% JBV)</b></td>
						<td>90% NPC <b>(~93% JBV)</td>
					</tr>
					<tr>
						<td class="table-danger">Red Loot</td>
						<td>92% NPC <b>(~95% JBV)</b></td>
						<td>90% NPC <b>(~93% JBV)</td>
					</tr>
					<tr>
						<td class="table-primary">Blue Loot</td>
						<td>92% NPC <b>(~95% JBV)</b></td>
						<td>90% NPC <b>(~93% JBV)</td>
					</tr>
					<tr>
						<td>Salvage</td>
						<td>94% JBV</td>
						<td>92% JBV</td>
					</tr>
					<tr>
						<td>Datacores</td>
						<td>94% JBV</td>
						<td>92% JBV</td>
					</tr>
					<tr>
						<td>Decryptors</td>
						<td>94% JBV</td>
						<td>92% JBV</td>
					</tr>
					<tr>
						<td>Implants</td>
						<td>94% JBV</td>
						<td>92% JBV</td>
					</tr>
					<tr>
						<td>Rat Poop</td>
						<td>92% JBV</td>
						<td>90% JBV</td>
					</tr>
					<tr>
						<td>Modules & Rigs</td>
						<td>92% JBV</td>
						<td>90% JBV</td>
					</tr>
					<tr>
						<td>Everything Else</td>
						<td>92% JBV</td>
						<td>90% JBV</td>
					</tr>
				</tbody>
			</table>
			*see below for effective rates on higher tier OPEs<br><br>
			<table class="table table-sm">
				<thead>
					<tr>
						<th scope="col">Overseer Effects</th>
						<th scope="col">Effective Payout</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>23rd Tier</td>
						<td>123m</td>
					</tr>
					<tr>
						<td>22nd Tier</td>
						<td>94m</td>
					</tr>
					<tr>
						<td>21st Tier</td>
						<td>74m</td>
					</tr>
					<tr>
						<td>20th Tier</td>
						<td>56m</td>
					</tr>
					<tr>
						<td>19th Tier</td>
						<td>47m</td>
					</tr>
				</tbody>
			</table>
			<p class="text-danger"><b>Not accepting blueprints, PI, ore, minerals, or ships.</b> I sometimes accept ships on a limited basis, but please <a href="/contact">contact me</a> beforehand.</p>
			<h4 id="getting-paid">How to get paid:</h4>
			<p><b>The Easy Way:</b> Create a contract to <a target="_blank" href="https://evemaps.dotlan.net/corp/Two_Trees">Two Trees</a> with a price of 0. I do all of the math and deposit your isk.</p>
			<p><b>The Slightly Harder Way:</b> Create a contract using the location-appropriate price produced by <a href="/">my calculator</a>.</p>
			<p><b>The Hardest Way:</b> Create an <a target="_blank" href="https://evepraisal.com/">Evepraisal</a> of the items, multiply 'Total Buy Value' by 0.9 (use 0.92 if located in a hub) or use the Price Percentage option in the gear menu, then create a contract with the calculated price. Note that you will NOT receive the higher rates on specific item groups with this method.</p>
			<br>
			<a target="_blank" href="https://forum.pleaseignore.com/topic/109678-active-two-trees-buyback/">Link to the service post on the TEST Forums (requires TEST Auth)</a>
		</div>
	</div>
</div>
{% endblock %}
